language: c
dist: xenial
sudo: required
arch:
  - amd64
  - arm64
branches:
  only:
  - master
  - develop
os:
  - linux
git:
  submodules: false
services:
  - xvfb
before_install:
  - git submodule update --init --recursive
compiler:
  - clang
  - gcc
env:
  - TRAVIS_PYTHON_VERSION=3.7 TESTS_EXCLUDE_RE='^test_[a-p].*\.py'
  - TRAVIS_PYTHON_VERSION=3.7 TESTS_EXCLUDE_RE='^test_[^a-p].*\.py'
notifications:
  email: false
install: source continuous_integration/install.sh
script: bash continuous_integration/test_script.sh --exclude="$TESTS_EXCLUDE_RE"
